# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.7-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     # - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit


  web:
    build: .
    ports:
      - "8080:8080"
    # "зависит от",
    depends_on:
      - db
    # переменные окружения
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
