drop table if exists booking;
drop table if exists requests;
drop table if exists comments;
drop table if exists items;
drop table if exists users;


CREATE TABLE IF NOT EXISTS users
(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME   VARCHAR(50) NOT NULL,
    EMAIL  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    description VARCHAR(500),
    IS_AVAILABLE BOOLEAN,
    owner_id BIGINT REFERENCES users (id),
    request_id BIGINT
    );

CREATE TABLE IF NOT EXISTS booking
(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT REFERENCES items (id),
    user_id BIGINT REFERENCES users (id),
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS requests
(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(500),
    user_id BIGINT REFERENCES users (id),
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE TABLE IF NOT EXISTS comments
(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1000),
    item_id BIGINT REFERENCES items (id),
    user_id BIGINT REFERENCES users (id),
    created TIMESTAMP WITHOUT TIME ZONE
    );

